import type { NextPage } from 'next';
import Head from 'next/head';
import MasterHead from '../components/MasterHead';
import Vision from '../components/Vision';

const Home: NextPage = () => {
  return (
    <div className='bg-black antialiased text-white'>
      <Head>
        <title>Invoice</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MasterHead />
      <Vision />
    </div>
  );
};

export default Home;
